// Mock user credentials
export const mockUsers = [
  { phone: "+919876543210", name: "Rajesh Kumar", city: "Prayagraj", otp: "123456", userType: "landlord" as const },
  { phone: "+919876543211", name: "Sunita Devi", city: "Prayagraj", otp: "123456", userType: "landlord" as const },
  { phone: "+919999999999", name: "Demo Landlord", city: "Delhi", otp: "123456", userType: "landlord" as const },
  // Student accounts
  {
    phone: "+919111111111",
    name: "Rahul Verma",
    city: "Prayagraj",
    otp: "123456",
    userType: "student" as const,
    college: "IIIT Allahabad",
    course: "B.Tech CSE",
  },
  {
    phone: "+919222222222",
    name: "Priya Singh",
    city: "Delhi",
    otp: "123456",
    userType: "student" as const,
    college: "Delhi University",
    course: "B.Com Honours",
  },
  {
    phone: "+919333333333",
    name: "Amit Patel",
    city: "Kota",
    otp: "123456",
    userType: "student" as const,
    college: "Allen Career Institute",
    course: "IIT-JEE Prep",
  },
]

export interface Listing {
  id: string
  title: string
  description: string
  type: "pg" | "flat" | "hostel" | "room"
  forGender: "boys" | "girls" | "any"
  occupancy: "single" | "double" | "triple" | "dorm"
  city: string
  area: string
  landmark: string
  rent: number
  deposit: number
  includesFood: boolean
  electricityType: "included" | "extra"
  amenities: string[]
  imageUrls: string[]
  ownerName: string
  ownerPhone: string
  ownerWhatsapp?: string
  status: "pending" | "approved" | "hidden"
  createdAt: string
  ownerId?: string
  isAvailable: boolean
  isVerified: boolean
  views: number
}

export const cities: Record<string, string[]> = {
  Prayagraj: [
    "Civil Lines",
    "Naini",
    "Katra",
    "Tagore Town",
    "Mumfordganj",
    "George Town",
    "Jhunsi",
    "Phaphamau",
    "Allahpur",
    "Lukerganj",
  ],
  Delhi: [
    "Connaught Place",
    "Karol Bagh",
    "Dwarka",
    "Rohini",
    "Pitampura",
    "Lajpat Nagar",
    "Saket",
    "Vasant Kunj",
    "Janakpuri",
    "Rajouri Garden",
    "Kamla Nagar",
    "GTB Nagar",
    "Mukherjee Nagar",
  ],
  Mumbai: ["Andheri", "Bandra", "Powai", "Dadar", "Lower Parel", "Malad", "Goregaon", "Thane", "Borivali", "Vashi"],
  Bangalore: [
    "Koramangala",
    "Indiranagar",
    "HSR Layout",
    "Whitefield",
    "Electronic City",
    "Marathahalli",
    "BTM Layout",
    "Jayanagar",
    "JP Nagar",
    "Hebbal",
  ],
  Hyderabad: [
    "Madhapur",
    "Hitech City",
    "Gachibowli",
    "Kondapur",
    "Banjara Hills",
    "Jubilee Hills",
    "Kukatpally",
    "Ameerpet",
    "Begumpet",
    "Secunderabad",
  ],
  Chennai: [
    "T Nagar",
    "Anna Nagar",
    "Velachery",
    "Adyar",
    "OMR",
    "Tambaram",
    "Porur",
    "Guindy",
    "Nungambakkam",
    "Mylapore",
  ],
  Kolkata: [
    "Salt Lake",
    "Park Street",
    "New Town",
    "Howrah",
    "Dum Dum",
    "Jadavpur",
    "Garia",
    "Behala",
    "Lake Gardens",
    "Ballygunge",
  ],
  Pune: [
    "Koregaon Park",
    "Hinjewadi",
    "Kothrud",
    "Wakad",
    "Baner",
    "Viman Nagar",
    "Hadapsar",
    "Kharadi",
    "Aundh",
    "Shivajinagar",
  ],
  Jaipur: [
    "Malviya Nagar",
    "Vaishali Nagar",
    "Raja Park",
    "C Scheme",
    "Mansarovar",
    "Jagatpura",
    "Tonk Road",
    "Sodala",
    "Bani Park",
    "MI Road",
  ],
  Lucknow: [
    "Gomti Nagar",
    "Hazratganj",
    "Aliganj",
    "Indira Nagar",
    "Mahanagar",
    "Alambagh",
    "Rajajipuram",
    "Chinhat",
    "Jankipuram",
    "Vikas Nagar",
  ],
  Ahmedabad: [
    "Navrangpura",
    "Satellite",
    "Prahlad Nagar",
    "SG Highway",
    "Bodakdev",
    "Vastrapur",
    "Maninagar",
    "Gota",
    "Chandkheda",
    "Thaltej",
  ],
  Chandigarh: [
    "Sector 17",
    "Sector 22",
    "Sector 35",
    "Sector 43",
    "Sector 44",
    "Mohali",
    "Panchkula",
    "Zirakpur",
    "IT Park",
    "Industrial Area",
  ],
  Noida: [
    "Sector 62",
    "Sector 18",
    "Sector 63",
    "Sector 15",
    "Sector 50",
    "Sector 76",
    "Greater Noida",
    "Noida Extension",
    "Sector 137",
    "Sector 125",
  ],
  Gurgaon: [
    "DLF Phase 1",
    "DLF Phase 2",
    "Sohna Road",
    "Golf Course Road",
    "Sector 56",
    "Sector 49",
    "MG Road",
    "Cyber City",
    "Sector 82",
    "Palam Vihar",
  ],
  Kota: [
    "Talwandi",
    "Mahaveer Nagar",
    "Vigyan Nagar",
    "Kunhari",
    "Dadabari",
    "Borkhera",
    "Jawahar Nagar",
    "Rangbari",
    "Indraprastha",
    "Gumanpura",
  ],
}

export const allCities = Object.keys(cities)

export function getAreasForCity(city: string): string[] {
  return cities[city] || []
}

export const areas = cities["Prayagraj"]

export const amenities = [
  "WiFi",
  "AC",
  "Food",
  "Laundry",
  "Parking",
  "CCTV",
  "Power Backup",
  "Geyser",
  "Furnished",
  "Attached Washroom",
  "Study Table",
  "Wardrobe",
  "TV",
  "Refrigerator",
  "Washing Machine",
  "Kitchen Access",
  "Gym",
  "Swimming Pool",
  "Lift",
  "Security Guard",
  "RO Water",
  "Housekeeping",
  "Balcony",
  "Garden View",
]

export const demoListings: Listing[] = [
  {
    id: "1",
    title: "Spacious Single Room PG near IIIT",
    description:
      "Well-maintained single occupancy room with attached bathroom. Perfect for students. 24/7 water supply and power backup available.",
    type: "pg",
    forGender: "boys",
    occupancy: "single",
    city: "Prayagraj",
    area: "Jhunsi",
    landmark: "Near IIIT Allahabad Main Gate",
    rent: 6500,
    deposit: 10000,
    includesFood: true,
    electricityType: "extra",
    amenities: ["WiFi", "Food", "Attached Washroom", "Study Table", "Power Backup"],
    imageUrls: [
      "/cozy-student-room-with-bed-and-study-desk.jpg",
      "/student-room-interior-2.jpg",
      "/bathroom-modern.jpg",
    ],
    ownerName: "Rajesh Kumar",
    ownerPhone: "+919876543210",
    ownerWhatsapp: "+919876543210",
    status: "approved",
    createdAt: "2024-01-15",
    isAvailable: true,
    isVerified: true,
    views: 156,
  },
  {
    id: "2",
    title: "Girls Hostel - Civil Lines",
    description:
      "Safe and secure girls hostel with warden facility. Homely food served twice a day. Close to coaching centers.",
    type: "hostel",
    forGender: "girls",
    occupancy: "double",
    city: "Prayagraj",
    area: "Civil Lines",
    landmark: "Near Civil Lines Bus Stand",
    rent: 5500,
    deposit: 8000,
    includesFood: true,
    electricityType: "included",
    amenities: ["WiFi", "Food", "CCTV", "Geyser", "Wardrobe", "Laundry"],
    imageUrls: ["/clean-girls-hostel-room-with-two-beds.jpg", "/hostel-common-area.jpg", "/hostel-dining.jpg"],
    ownerName: "Sunita Devi",
    ownerPhone: "+919876543211",
    ownerWhatsapp: "+919876543211",
    status: "approved",
    createdAt: "2024-01-20",
    isAvailable: true,
    isVerified: true,
    views: 243,
  },
  {
    id: "3",
    title: "Furnished 2BHK Flat for Students",
    description:
      "Fully furnished 2BHK flat ideal for group of students. Separate rooms, kitchen, and living area. Prime location.",
    type: "flat",
    forGender: "any",
    occupancy: "triple",
    city: "Prayagraj",
    area: "Tagore Town",
    landmark: "Near Tagore Town Market",
    rent: 15000,
    deposit: 30000,
    includesFood: false,
    electricityType: "extra",
    amenities: ["WiFi", "AC", "Furnished", "Parking", "Geyser", "Power Backup", "Kitchen Access", "Balcony"],
    imageUrls: ["/modern-furnished-apartment-living-room.jpg", "/flat-bedroom.jpg", "/flat-kitchen-modern.jpg"],
    ownerName: "Amit Sharma",
    ownerPhone: "+919876543212",
    status: "approved",
    createdAt: "2024-02-01",
    isAvailable: true,
    isVerified: false,
    views: 89,
  },
  {
    id: "4",
    title: "Budget PG in Naini",
    description:
      "Affordable PG accommodation with basic amenities. Good for students looking for budget options near Naini college.",
    type: "pg",
    forGender: "boys",
    occupancy: "double",
    city: "Prayagraj",
    area: "Naini",
    landmark: "Near Naini Central Jail",
    rent: 3500,
    deposit: 5000,
    includesFood: false,
    electricityType: "included",
    amenities: ["WiFi", "Study Table", "Wardrobe"],
    imageUrls: ["/simple-budget-room-with-two-beds.jpg"],
    ownerName: "Vijay Singh",
    ownerPhone: "+919876543213",
    ownerWhatsapp: "+919876543213",
    status: "approved",
    createdAt: "2024-02-10",
    isAvailable: false,
    isVerified: true,
    views: 312,
  },
  {
    id: "5",
    title: "Premium AC Room - Mumfordganj",
    description:
      "Luxury single room with AC, attached bathroom, and premium furniture. Ideal for professionals and students.",
    type: "room",
    forGender: "any",
    occupancy: "single",
    city: "Prayagraj",
    area: "Mumfordganj",
    landmark: "Near Prayagraj Junction",
    rent: 9000,
    deposit: 15000,
    includesFood: false,
    electricityType: "extra",
    amenities: ["WiFi", "AC", "Furnished", "Attached Washroom", "Geyser", "CCTV", "TV", "Refrigerator"],
    imageUrls: ["/premium-ac-room-with-modern-furniture.jpg", "/premium-room-bathroom.jpg", "/ac-room-view.jpg"],
    ownerName: "Priya Verma",
    ownerPhone: "+919876543214",
    status: "approved",
    createdAt: "2024-02-15",
    isAvailable: true,
    isVerified: true,
    views: 178,
  },
  {
    id: "6",
    title: "Girls PG with Homely Food",
    description: "Safe and comfortable PG for girls with homemade vegetarian food. Near major coaching institutes.",
    type: "pg",
    forGender: "girls",
    occupancy: "double",
    city: "Prayagraj",
    area: "Katra",
    landmark: "Near Katra Market",
    rent: 6000,
    deposit: 10000,
    includesFood: true,
    electricityType: "included",
    amenities: ["WiFi", "Food", "Geyser", "CCTV", "Laundry", "Wardrobe", "RO Water"],
    imageUrls: ["/cozy-girls-pg-room-with-beds.jpg"],
    ownerName: "Meera Agarwal",
    ownerPhone: "+919876543215",
    ownerWhatsapp: "+919876543215",
    status: "approved",
    createdAt: "2024-02-20",
    isAvailable: true,
    isVerified: false,
    views: 201,
  },
  {
    id: "7",
    title: "Modern PG in Koramangala",
    description: "Premium PG accommodation in the heart of Koramangala. Walking distance to major tech parks.",
    type: "pg",
    forGender: "boys",
    occupancy: "single",
    city: "Bangalore",
    area: "Koramangala",
    landmark: "Near Forum Mall",
    rent: 12000,
    deposit: 24000,
    includesFood: true,
    electricityType: "included",
    amenities: ["WiFi", "Food", "AC", "Laundry", "CCTV", "Gym", "Power Backup"],
    imageUrls: ["/modern-bangalore-pg-room-with-ac.jpg", "/pg-gym-facility.jpg", "/pg-common-area-modern.jpg"],
    ownerName: "Karthik Reddy",
    ownerPhone: "+919876543216",
    ownerWhatsapp: "+919876543216",
    status: "approved",
    createdAt: "2024-02-25",
    isAvailable: true,
    isVerified: true,
    views: 445,
  },
  {
    id: "8",
    title: "Bandra West Shared Flat",
    description: "Beautiful shared apartment in prime Bandra location. Sea-facing balcony with modern amenities.",
    type: "flat",
    forGender: "any",
    occupancy: "double",
    city: "Mumbai",
    area: "Bandra",
    landmark: "Near Bandstand",
    rent: 18000,
    deposit: 36000,
    includesFood: false,
    electricityType: "extra",
    amenities: ["WiFi", "AC", "Furnished", "Parking", "Power Backup", "CCTV", "Balcony", "Lift", "Security Guard"],
    imageUrls: ["/mumbai-flat-with-sea-view-balcony.jpg", "/sea-view-balcony.jpg", "/modern-flat-living-room.jpg"],
    ownerName: "Rohit Mehta",
    ownerPhone: "+919876543217",
    status: "approved",
    createdAt: "2024-03-01",
    isAvailable: true,
    isVerified: true,
    views: 567,
  },
  {
    id: "9",
    title: "Student Hostel Near DU",
    description: "Affordable hostel for Delhi University students. 5 mins walk from North Campus.",
    type: "hostel",
    forGender: "boys",
    occupancy: "triple",
    city: "Delhi",
    area: "Kamla Nagar",
    landmark: "Near Delhi University",
    rent: 7000,
    deposit: 14000,
    includesFood: true,
    electricityType: "included",
    amenities: ["WiFi", "Food", "Study Table", "Laundry", "CCTV", "RO Water", "Housekeeping"],
    imageUrls: ["/delhi-university-hostel-room.jpg"],
    ownerName: "Suresh Gupta",
    ownerPhone: "+919876543218",
    ownerWhatsapp: "+919876543218",
    status: "approved",
    createdAt: "2024-03-05",
    isAvailable: true,
    isVerified: true,
    views: 389,
  },
  {
    id: "10",
    title: "Kota Coaching PG",
    description: "Specialized PG for IIT/Medical aspirants. Quiet study environment with dedicated study halls.",
    type: "pg",
    forGender: "boys",
    occupancy: "double",
    city: "Kota",
    area: "Talwandi",
    landmark: "Near Allen Coaching",
    rent: 8500,
    deposit: 17000,
    includesFood: true,
    electricityType: "included",
    amenities: ["WiFi", "Food", "Study Table", "AC", "Power Backup", "Laundry", "RO Water", "Housekeeping"],
    imageUrls: ["/kota-pg-room-for-students-preparing-for-exams.jpg", "/study-hall-kota.jpg", "/pg-mess-dining.jpg"],
    ownerName: "Dinesh Sharma",
    ownerPhone: "+919876543219",
    ownerWhatsapp: "+919876543219",
    status: "approved",
    createdAt: "2024-03-10",
    isAvailable: true,
    isVerified: true,
    views: 623,
  },
]
